Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "centos/8"

  config.vm.define "r1" do |config|
    config.vm.hostname = "r1"
    config.vm.network "private_network", :ip => "10.20.1.1", :netmask => "255.255.255.0", :virtualbox__intnet => "r1", :libvirt__network_name => 'r1', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.network "private_network", :ip => "10.10.1.1", :netmask => "255.255.255.0", :virtualbox__intnet => "peers", :libvirt__network_name => 'peers', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.provision "bgp", type: "shell", path: "r1.sh"
  end 
  
  config.vm.define "r2" do |config|
    config.vm.hostname = "r2"
    config.vm.network "private_network", :ip => "10.10.1.2", :netmask => "255.255.255.0", :virtualbox__intnet => "peers", :libvirt__network_name => 'peers', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.network "private_network", :ip => "10.30.1.1", :netmask => "255.255.255.0", :virtualbox__intnet => "r2", :libvirt__network_name => 'r2', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.provision "shell", inline: "yum -y upgrade kernel"
    config.vm.provision :reload
    config.vm.provision "file", source: "../CMakeLists.txt", destination: "$HOME/anycast_roaming/CMakeLists.txt"
    config.vm.provision "file", source: "../src/CMakeLists.txt", destination: "$HOME/anycast_roaming/src/CMakeLists.txt"
    config.vm.provision "file", source: "../src/core.c", destination: "$HOME/anycast_roaming/src/core.c"
    config.vm.provision "file", source: "../src/Kbuild.default", destination: "$HOME/anycast_roaming/src/Kbuild.default"
    config.vm.provision "bgp", type: "shell", path: "r2.sh"
  end
  
  config.vm.define "r3" do |config|
    config.vm.hostname = "r3"
    config.vm.network "private_network", :ip => "10.10.1.3", :netmask => "255.255.255.0", :virtualbox__intnet => "peers", :libvirt__network_name => 'peers', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.network "private_network", :ip => "10.30.1.1", :netmask => "255.255.255.0", :virtualbox__intnet => "r3", :libvirt__network_name => 'r3', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.provision "shell", inline: "yum -y upgrade kernel"
    config.vm.provision :reload
    config.vm.provision "file", source: "../CMakeLists.txt", destination: "$HOME/anycast_roaming/CMakeLists.txt"
    config.vm.provision "file", source: "../src/CMakeLists.txt", destination: "$HOME/anycast_roaming/src/CMakeLists.txt"
    config.vm.provision "file", source: "../src/core.c", destination: "$HOME/anycast_roaming/src/core.c"
    config.vm.provision "file", source: "../src/Kbuild.default", destination: "$HOME/anycast_roaming/src/Kbuild.default"
    config.vm.provision "bgp", type: "shell", path: "r3.sh"
  end

  config.vm.define "s1" do |config|
    config.vm.hostname = "s1"
    config.vm.network "private_network", :ip => "10.30.1.2", :netmask => "255.255.255.0", :virtualbox__intnet => "r2", :libvirt__network_name => 'r2', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--natnet1", "10.1.0.0/24"]
    end
    config.vm.provision "app", type: "shell", path: "s1.sh"
    
  end 
  
  config.vm.define "s2" do |config|
    config.vm.hostname = "s2"
    config.vm.network "private_network", :ip => "10.30.1.2", :netmask => "255.255.255.0", :virtualbox__intnet => "r3", :libvirt__network_name => 'r3', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false
    config.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--natnet1", "10.2.0.0/24"]
    end
    config.vm.provision "app", type: "shell", path: "s2.sh"
    
  end 
  
  config.vm.define "user" do |config|
    config.vm.hostname = "user"
    config.vm.network "private_network", :ip => "10.20.1.100", :netmask => "255.255.255.0", :virtualbox__intnet => "r1", :libvirt__network_name => 'r1', :libvirt__forward_mode => 'veryisolated', :libvirt__dhcp_enabled => false

    config.vm.provision "shell", inline: "yum -y install net-tools mtr"
    config.vm.provision "shell", inline: "route add -net 10.10.1.0/24 gw 10.20.1.1"
    config.vm.provision "shell", inline: "route add -net 10.30.1.0/24 gw 10.20.1.1"

  end
end
